version: '3'
services:
  app:
    ports:
      - 80:80
    build:
      # build the actual app
      context: ../../
      dockerfile: compose/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_CHANNEL_URL: ${VITE_CHANNEL_URL}
        VITE_CHANNEL_KEY: ${VITE_CHANNEL_KEY}
    restart: on-failure
    labels:
        caddy: ${DOMAIN}
        caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy: {}